export const CHANGE_SEARCHING = "CHANGE_SEARCHING";
export const REQ_POKEMON_PENDING = "REQ_POKEMON_PENDING";
export const REQ_POKEMON_SUCCESS = "REQ_POKEMON_SUCCESS";
export const REQ_POKEMON_FAILED = "REQ_POKEMON_FAILED";
